// <auto-generated />
using Backend.Api.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Backend.Api.Migrations
{
    [DbContext(typeof(BackendDb))]
    [Migration("20180319051657_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Backend.Api.Entities.Rol", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Backend.Api.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(44);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(24);

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Backend.Api.Entities.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId");

                    b.Property<string>("RolId");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios_Roles");
                });

            modelBuilder.Entity("Backend.Api.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Backend.Api.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Api.Entities.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
